import 'lucide-react'

// Re-export lucide-react icons for convenience
export { default as Menu } from 'lucide-react'
export { default as X } from 'lucide-react'
export { default as Zap } from 'lucide-react'
export { default as Users } from 'lucide-react'
export { default as TrendingUp } from 'lucide-react'
export { default as Code } from 'lucide-react'
export { default as Github } from 'lucide-react'
// export { default as Linkedin } from 'lucide-react' // Removed, not used
export { default as Mail } from 'lucide-react'
export { default as Twitter } from 'lucide-react'
export { default as BarChart3 } from 'lucide-react'
export { default as CheckCircle } from 'lucide-react'
export { default as AlertCircle } from 'lucide-react'
export { default as Search } from 'lucide-react'
export { default as Star } from 'lucide-react'
export { default as MapPin } from 'lucide-react'
export { default as Phone } from 'lucide-react'
export { default as FileText } from 'lucide-react'
export { default as Database } from 'lucide-react'
export { default as Shield } from 'lucide-react'
